footprint: [[-0.2, -0.2], [-0.2, 0.2], [0.2, 0.2], [0.2, -0.2]]
footprint_padding: 0.01

robot_base_frame: clover2/robot_footprint
update_frequency: 1.0
publish_frequency: 2.0
transform_tolerance: 6.0

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: laser/scan, inf_is_valid: true}

inflation:
    inflation_radius: 0.08
