base_frame: robot_footprint
map_frame: map
odom_frame: odom
map_update_interval: 0.5
maxUrange: 25.0
maxRange: 30.0
transform_publish_period: 0.

minimumScore: 100

linearUpdate: 0.2
angularUpdate: 0.336
temporalUpdate: -1.0
resampleThreshold: 0.5
particles: 50
xmin: -50.0
ymin: -50.0
xmax: 50.0
ymax: 50.0

delta: 0.05
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
